
spring:
  jpa:
    hibernate:
      ddl-auto: validate

  application:
    name: api
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/krampoline

springdoc:
  swagger-ui:
    path: /api/doc2
    use-root-path: true
    disable-swagger-default-url: true
